### ISSUE TITLE
The current tab name should be reflected in the window title.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/desktop#232]

**Comment by pdobacz** [comment]
@cristianberneanu This should include also the "special" `Documentation` tab, so that the window title says `Documentation - Diffix for Desktop` when that's selected, right? no magic involved to recognize which notebook tab the user is working on? That wouldn't be too hard, but maybe not worth the complication?

**Comment by cristianberneanu** [comment]
Right, no need to add a special case for the "Documentation" tab.
